import { Experience } from '@/types/experience'

export const ExperienceData: Experience[] = [
  {
    name: 'Popupsmart',
    icon: '/assets/icons/popupsmart.svg',
    path: 'https://popupsmart.com/',
    date: '21 February 2024 - 22 July 2024',
    position: 'Intern Software Developer',
    projects: [
      {
        name: 'Website Audit AI',
        path: 'https://websiteauditai.com/',
        description: 'AI-Powered Website Audit and CRO & UX Analysis',
        whatIDid: [
          `<b>Developed the entire project by myself</b>`,
          'Supabase integrations for user authentication processes and data storage',
          'OpenAI Vision API for image analysis with prompts',
          'UI development all over the project',
          'Store management with Zustand',
          'Stripe integration for payment processing',
          'PDF export for the audit report with using the Puppeteer',
        ],
        stack: [
          'Next.js',
          'TypeScript',
          'Zustand',
          'Tailwind CSS',
          'shadcn/ui',
          'Supabase',
          'OpenAI API',
          'Langchain',
          'Stripe',
          'Vercel',
        ],
      },
    ],
  },
  {
    name: 'Popupsmart',
    icon: '/assets/icons/popupsmart.svg',
    path: 'https://popupsmart.com/',
    date: '22 July 2024 - Present',
    position: 'Software Developer',
    projects: [
      {
        name: 'HR Assistant AI',
        path: 'https://hrassistantai.com/',
        description:
          'HR Assistant AI is an AI-powered tool designed to automate and streamline various HR tasks using artificial intelligence. It helps manage in-house questions with automated answers and reduce repetitive tasks.',
        whatIDid: [
          'UI development with shadcn/ui package (Auth, Billing, Profile and Dashboard pages)',
          'API endpoints for forgot, new and update password and billing processes',
          'Modal management for user interactions',
          'Stripe integration for payment processing',
          'Error handling and form validations',
          'Creating Hooks for UI animations',
          'Responsive design for mobile and desktop views',
        ],
        stack: [
          'Next.js',
          'Next Auth',
          'TypeScript',
          'Redux / Redux Toolkit',
          'Zustand',
          'Tailwind CSS',
          'shadcn/ui',
          'Langchain',
          'Prisma',
          'Stripe',
        ],
      },
      {
        name: 'LiveChatAI',
        path: 'https://livechatai.com/',
        description:
          'LiveChatAI, your ultimate AI bot architect. Harnessing the capabilities of ChatGPT, it tailors your data into an interactive chat widget for your website.',
        whatIDid: [
          'UX flow improvements (User deleting, AI Actions)',
          'React Query mutations, Zustand store management',
          'UI improvements and bug fixes',
          'Prisma migrations, schema updates and functions',
          'Creating API endpoints for actions',
        ],
        stack: [
          'Next.js',
          'Next Auth',
          'TypeScript',
          'Redux / Redux Toolkit',
          'Zustand',
          'React-Query - Tanstack',
          'Tailwind CSS / SASS',
          'Langchain',
          'Prisma',
          'Stripe',
          'Posthog',
        ],
      },
    ],
  },
]
